# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
  selector:
    app: ollama
